### ISSUE TITLE
Branches should be cleaned up

### ISSUE THREAD

**Issue by mherrmann** [brave/omaha#38]
At the moment, brave-core points at commit a199d4a386798c4ecc1a29f1a80f58a1da4755ff of this repository. None of the branches in this repo point there:

- `rebase-v1.3.36.111` points at one commit ahead of the above commit.
- `main` has some doc improvements but is otherwise entirely outdated.
- `master` is even more outdated.

In my opinion, `main` should be updated to point at the above commit (or whichever the current commit is in brave-browser/DEPS), the doc improvements should be incorporated there, and the other branches should be deleted.

**Comment by mihaiplesa** [comment]
Removed `master` and planning to have `main` as the default after merging your recent PRs.

**Comment by mihaiplesa** [comment]
Enabled auto deletion of merged branches, removed `main` and renamed default branch (with the latest code) to `main`.
