### ISSUE TITLE
Use parallel builds

### ISSUE THREAD

**Issue by mherrmann** [brave/omaha#44]
`hammer.bat` supports parallel builds with the `-j` option. E.g. `hammer.bat -j32` for building with 32 cores. This significantly speeds up build times. The goal of this issue is to make `build_omaha.py` pass a suitable `-j` value to `hammer.bat` when building, and thus to likewise speed up Brave's build (`create_dist --build_omaha`) on Windows.

**Comment by mihaiplesa** [comment]
Can we just pass the same j value that gets computed for the other stages of the build?

**Comment by mherrmann** [comment]
Yes, I believe that should work. I use the number of cores as the `-j` value.
